version: '3.8'
 
services:
  smartkrow-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_REGION=
      - bucket-name=
      - EXPIRE_URL_MINUTES=60
    networks:
      - my-network
 
networks:
  my-network:
    driver: bridge
