version: '3.8'
 
services:
  smartkrow-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - my-network
 
networks:
  my-network:
    driver: bridge
