package com.smartKrow.constants;

public class MasterDataConstant {

	public static final String masterData = "{\r\n"
			+ "    \"resultData\": [\r\n"
			+ "        {\r\n"
			+ "            \"displayName\": \"EER Batches\",\r\n"
			+ "            \"entityName\": \"ZAPEMPEXP\",\r\n"
			+ "            \"searchFields\": [\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"COCD\",\r\n"
			+ "                    \"displayName\": \"COCD\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                },\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"doc_Number\",\r\n"
			+ "                    \"displayName\": \"Document Number\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                },\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"year\",\r\n"
			+ "                    \"displayName\": \"Year\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                }\r\n"
			+ "            ],\r\n"
			+ "            \"entity_id\": \"1\",\r\n"
			+ "            \"type\": \"FNCA\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"displayName\": \"GFF Urgent Payment\",\r\n"
			+ "            \"entityName\": \"ZAPGFFUP\",\r\n"
			+ "            \"searchFields\": [\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"COCD\",\r\n"
			+ "                    \"displayName\": \"COCD\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                },\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"doc_Number\",\r\n"
			+ "                    \"displayName\": \"Document Number\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                },\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"year\",\r\n"
			+ "                    \"displayName\": \"Year\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                }\r\n"
			+ "            ],\r\n"
			+ "            \"entity_id\": \"2\",\r\n"
			+ "            \"type\": \"FNCA\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"displayName\": \"LARA Intermodal & 3PF\",\r\n"
			+ "            \"entityName\": \"ZAPLARINV\",\r\n"
			+ "            \"searchFields\": [\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"COCD\",\r\n"
			+ "                    \"displayName\": \"COCD\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                },\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"doc_Number\",\r\n"
			+ "                    \"displayName\": \"Document Number\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                },\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"year\",\r\n"
			+ "                    \"displayName\": \"Year\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                }\r\n"
			+ "            ],\r\n"
			+ "            \"entity_id\": \"3\",\r\n"
			+ "            \"type\": \"FNCA\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"displayName\": \"Non-PO Credit Memo\",\r\n"
			+ "            \"entityName\": \"ZAPNPCRMEM\",\r\n"
			+ "            \"searchFields\": [\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"COCD\",\r\n"
			+ "                    \"displayName\": \"COCD\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                },\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"doc_Number\",\r\n"
			+ "                    \"displayName\": \"Document Number\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                },\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"year\",\r\n"
			+ "                    \"displayName\": \"Year\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                }\r\n"
			+ "            ],\r\n"
			+ "            \"entity_id\": \"4\",\r\n"
			+ "            \"type\": \"FNCA\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"displayName\": \"Incoming PO invoice / Vendor PO\\n Credit Memo\",\r\n"
			+ "            \"entityName\": \"ZAPPOINV\",\r\n"
			+ "            \"searchFields\": [\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"COCD\",\r\n"
			+ "                    \"displayName\": \"COCD\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                },\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"doc_Number\",\r\n"
			+ "                    \"displayName\": \"Document Number\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                },\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"year\",\r\n"
			+ "                    \"displayName\": \"Year\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                }\r\n"
			+ "            ],\r\n"
			+ "            \"entity_id\": \"5\",\r\n"
			+ "            \"type\": \"FNCA\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"displayName\": \"VTO Invoice\",\r\n"
			+ "            \"entityName\": \"ZAPPVTO\",\r\n"
			+ "            \"searchFields\": [\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"COCD\",\r\n"
			+ "                    \"displayName\": \"COCD\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                },\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"doc_Number\",\r\n"
			+ "                    \"displayName\": \"Document Number\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                },\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"year\",\r\n"
			+ "                    \"displayName\": \"Year\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                }\r\n"
			+ "            ],\r\n"
			+ "            \"entity_id\": \"6\",\r\n"
			+ "            \"type\": \"FNCA\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"displayName\": \"Urgent Payment\",\r\n"
			+ "            \"entityName\": \"ZAPUPDOO\",\r\n"
			+ "            \"searchFields\": [\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"COCD\",\r\n"
			+ "                    \"displayName\": \"COCD\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                },\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"doc_Number\",\r\n"
			+ "                    \"displayName\": \"Document Number\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                },\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"year\",\r\n"
			+ "                    \"displayName\": \"Year\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                }\r\n"
			+ "            ],\r\n"
			+ "            \"entity_id\": \"7\",\r\n"
			+ "            \"type\": \"FNCA\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"displayName\": \"Advance Payment\",\r\n"
			+ "            \"entityName\": \"ZAP-ADVDOO\",\r\n"
			+ "            \"searchFields\": [\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"COCD\",\r\n"
			+ "                    \"displayName\": \"COCD\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                },\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"doc_Number\",\r\n"
			+ "                    \"displayName\": \"Document Number\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                },\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"year\",\r\n"
			+ "                    \"displayName\": \"Year\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                }\r\n"
			+ "            ],\r\n"
			+ "            \"entity_id\": \"8\",\r\n"
			+ "            \"type\": \"FNCA\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"displayName\": \"Payment History Correction Form\",\r\n"
			+ "            \"entityName\": \"ZAPPHC\",\r\n"
			+ "            \"searchFields\": [\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"COCD\",\r\n"
			+ "                    \"displayName\": \"COCD\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                },\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"PHC_NUMBER\",\r\n"
			+ "                    \"displayName\": \"Phone Number\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                },\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"year\",\r\n"
			+ "                    \"displayName\": \"Year\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                }\r\n"
			+ "            ],\r\n"
			+ "            \"entity_id\": \"9\",\r\n"
			+ "            \"type\": \"FNCA\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"displayName\": \"Journal Supporting Doc\",\r\n"
			+ "            \"entityName\": \"ZFRJDOCO\",\r\n"
			+ "            \"searchFields\": [\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"COCD\",\r\n"
			+ "                    \"displayName\": \"COCD\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                },\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"DOC_NUMBER\",\r\n"
			+ "                    \"displayName\": \"DOCUMENT NUMBER\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                },\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"year\",\r\n"
			+ "                    \"displayName\": \"Year\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                }\r\n"
			+ "            ],\r\n"
			+ "            \"entity_id\": \"10\",\r\n"
			+ "            \"type\": \"FNCA\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"displayName\": \"GL Accrual\",\r\n"
			+ "            \"entityName\": \"ZGLACCR\",\r\n"
			+ "            \"searchFields\": [\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"COCD\",\r\n"
			+ "                    \"displayName\": \"COCD\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                },\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"DOC_NUMBER\",\r\n"
			+ "                    \"displayName\": \"DOCUMENT NUMBER\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                },\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"year\",\r\n"
			+ "                    \"displayName\": \"Year\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                }\r\n"
			+ "            ],\r\n"
			+ "            \"entity_id\": \"11\",\r\n"
			+ "            \"type\": \"FNCA\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"displayName\": \"Goods Mvmt Supporting Doc\",\r\n"
			+ "            \"entityName\": \"ZPCIMDOCT\",\r\n"
			+ "            \"searchFields\": [\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"MAT DOC\",\r\n"
			+ "                    \"displayName\": \"MAT_DOC\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                },\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"year\",\r\n"
			+ "                    \"displayName\": \"Year\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                }\r\n"
			+ "            ],\r\n"
			+ "            \"entity_id\": \"12\",\r\n"
			+ "            \"type\": \"FNCA\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"displayName\": \"PO Supporting  Doc\",\r\n"
			+ "            \"entityName\": \"ZPCPODOCO\",\r\n"
			+ "            \"searchFields\": [\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"VENDOR IDC\",\r\n"
			+ "                    \"displayName\": \"VENDOR_ID\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                },\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"POCREATION\",\r\n"
			+ "                    \"displayName\": \"POCREATION\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                },\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"PO_NUMBER\",\r\n"
			+ "                    \"displayName\": \"PO NUMBER\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                }\r\n"
			+ "            ],\r\n"
			+ "            \"entity_id\": \"13\",\r\n"
			+ "            \"type\": \"FNCA\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"displayName\": \"Vendor Evaluation Results PDF\",\r\n"
			+ "            \"entityName\": \"ZPCVNDEVP\",\r\n"
			+ "            \"searchFields\": [\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"VENDOR IDC\",\r\n"
			+ "                    \"displayName\": \"VENDOR_ID\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                },\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"CREATION DATE\",\r\n"
			+ "                    \"displayName\": \"CREATION DATE\",\r\n"
			+ "                    \"dataType\": \"Date\",\r\n"
			+ "                    \"isMandatory\": false,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                },\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"NAME2\",\r\n"
			+ "                    \"displayName\": \"NAME2\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": false,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                }\r\n"
			+ "            ],\r\n"
			+ "            \"entity_id\": \"14\",\r\n"
			+ "            \"type\": \"FNCA\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"displayName\": \"FT Supporting Docs\",\r\n"
			+ "            \"entityName\": \"ZTSFTDOCO\",\r\n"
			+ "            \"searchFields\": [\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"TRANSAC ID\",\r\n"
			+ "                    \"displayName\": \"TRANSAC_ID\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                },\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"CREATION DATE\",\r\n"
			+ "                    \"displayName\": \"CREATION DATE\",\r\n"
			+ "                    \"dataType\": \"Date\",\r\n"
			+ "                    \"isMandatory\": false,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                },\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"Start Date\",\r\n"
			+ "                    \"displayName\": \"START_DATE\",\r\n"
			+ "                    \"dataType\": \"Date\",\r\n"
			+ "                    \"isMandatory\": false,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                }\r\n"
			+ "            ],\r\n"
			+ "            \"entity_id\": \"15\",\r\n"
			+ "            \"type\": \"FNCA\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"displayName\": \"Asset Supporting Doc\",\r\n"
			+ "            \"entityName\": \"ZFADOCO\",\r\n"
			+ "            \"searchFields\": [\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"ASSET NUM\",\r\n"
			+ "                    \"displayName\": \"ASSET_NUM\",\r\n"
			+ "                    \"dataType\": \"Text\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                },\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"CREATION DATE\",\r\n"
			+ "                    \"displayName\": \"CREATION DATE\",\r\n"
			+ "                    \"dataType\": \"Date\",\r\n"
			+ "                    \"isMandatory\": false,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                }\r\n"
			+ "            ],\r\n"
			+ "            \"entity_id\": \"16\",\r\n"
			+ "            \"type\": \"FNCA\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"displayName\": \"Vendor Maintenance Sup Doc HTML\",\r\n"
			+ "            \"entityName\": \"ZVMVENDORH\",\r\n"
			+ "            \"searchFields\": [\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"VENDOR_ID\",\r\n"
			+ "                    \"displayName\": \"VENDOR ID\",\r\n"
			+ "                    \"dataType\": \"t\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                }\r\n"
			+ "            ],\r\n"
			+ "            \"entity_id\": \"17\",\r\n"
			+ "            \"type\": \"FNCA\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"displayName\": \"Vendor Maintenance Sup Doc  PDF\",\r\n"
			+ "            \"entityName\": \"ZVMVENDORP\",\r\n"
			+ "            \"searchFields\": [\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"VENDOR_ID\",\r\n"
			+ "                    \"displayName\": \"VENDOR ID\",\r\n"
			+ "                    \"dataType\": \"t\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                }\r\n"
			+ "            ],\r\n"
			+ "            \"entity_id\": \"18\",\r\n"
			+ "            \"type\": \"FNCA\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"displayName\": \"Vendor Maintenance Sup Doc TIFF\",\r\n"
			+ "            \"entityName\": \"ZVMVENDORT\",\r\n"
			+ "            \"searchFields\": [\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"VENDOR_ID\",\r\n"
			+ "                    \"displayName\": \"VENDOR ID\",\r\n"
			+ "                    \"dataType\": \"t\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                }\r\n"
			+ "            ],\r\n"
			+ "            \"entity_id\": \"19\",\r\n"
			+ "            \"type\": \"FNCA\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"displayName\": \"Freight Cash Image\",\r\n"
			+ "            \"entityName\": \"FCI\",\r\n"
			+ "            \"searchFields\": [\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"BATCH_ID\",\r\n"
			+ "                    \"displayName\": \"SCAN BATCH ID\",\r\n"
			+ "                    \"dataType\": \"Number\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                },\r\n"
			+ "                {\r\n"
			+ "                    \"fieldName\": \"BATCH_DATE\",\r\n"
			+ "                    \"displayName\": \"SCAN BATCH DATE\",\r\n"
			+ "                    \"dataType\": \"Date\",\r\n"
			+ "                    \"isMandatory\": true,\r\n"
			+ "                    \"status\": \"Active\"\r\n"
			+ "                }\r\n"
			+ "            ],\r\n"
			+ "            \"entity_id\": \"20\",\r\n"
			+ "            \"type\": \"FCI\"\r\n"
			+ "        }\r\n"
			+ "    ],\r\n"
			+ "    \"isSuccess\": \"Success\"\r\n"
			+ "}";
}
