package com.smartKrow.model;

import java.util.Date;
import java.util.HashMap;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedTimestamp;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@DynamoDBTable(tableName = "BulkProgressDownloadFiles")
@EqualsAndHashCode(callSuper = false)
public class BulkProgressDownloadStatus {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	@DynamoDBAttribute(attributeName = "document_id")
	private String documentId;

	@DynamoDBAttribute(attributeName = "documend_ids")
	private HashMap<String, Boolean> documentIds;

	@DynamoDBAttribute(attributeName = "download_link")
	private String downloadLink;

	@DynamoDBAttribute(attributeName = "entity_Name")
	private String entityName;

	@DynamoDBAttribute(attributeName = "creation_date")
	@DynamoDBTypeConvertedTimestamp
	private Date creationDate;

	@DynamoDBTypeConvertedTimestamp
	@DynamoDBAttribute(attributeName = "last_update_on")
	private Date lastUpdateDate;

	@DynamoDBAttribute(attributeName = "status")
	private String status;

	@DynamoDBAttribute(attributeName = "user_Id")
	private String userId;
	
	@DynamoDBAttribute(attributeName = "total_document")
	private Integer totalDocument;
	
	@DynamoDBAttribute(attributeName = "sucessfully_processed")
	private Integer successfullyProcessed;
	
	@DynamoDBAttribute(attributeName = "errors")
	private HashMap<String,String> errors;

}
