package com.smartKrow.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Data;

@Data
@DynamoDBTable(tableName = "FCI")
public class FCI extends CommonFields{

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	@DynamoDBAttribute(attributeName = "document_id")
	private String documentId;

	@DynamoDBAttribute(attributeName = "application_type")
	private String applicationType;

	@DynamoDBAttribute(attributeName = "APLL bL Number")
	private String apllBlnumber;

	@DynamoDBAttribute(attributeName = "Agent")
	private String agent;

	@DynamoDBAttribute(attributeName = "BL Number")
	private String blNumber;

	@DynamoDBAttribute(attributeName = "Cash Report Number")
	private String cashReportNumber;

	@DynamoDBAttribute(attributeName = "Document Processing Status")
	private String documnetProcessingStatus;

	@DynamoDBAttribute(attributeName = "Document type")
	private String documentType;

	@DynamoDBAttribute(attributeName = "f_entrydate")
	private String fEntryDate;

	@DynamoDBAttribute(attributeName = "Is Document Number")
	private String isDocumentNumber;

	@DynamoDBAttribute(attributeName = "No of Pages")
	private String noOfPages;

	@DynamoDBAttribute(attributeName = "Payment Amount")
	private String paymentAmount;

	@DynamoDBAttribute(attributeName = "Payment Date")
	private String paymentDate;

	@DynamoDBAttribute(attributeName = "Reference number")
	private String referenceNumber;

	@DynamoDBAttribute(attributeName = "Scan Batch ID")
	private String scanBatchId;

	@DynamoDBAttribute(attributeName = "DOCUMENT_LINK")
	private String documentLink;

}
