package com.smartKrow.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "ZAPPHC")
@EqualsAndHashCode(callSuper = false)
public class ZAPPHC extends CommonFields {
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	@DynamoDBAttribute(attributeName = "document_id")
	private String documentId;

	@DynamoDBAttribute(attributeName = "CONTENT_REP_TYP")
	private String contentRepTyp;
	
	@DynamoDBAttribute(attributeName = "application_type")
	private String applicationType;

	@DynamoDBAttribute(attributeName = "COCD")
	private String cocd;

	@DynamoDBAttribute(attributeName = "PHC_NUMBER")
	private String phcNumber;

	@DynamoDBAttribute(attributeName = "YEAR")
	private String year;
	
	@DynamoDBAttribute(attributeName = "POCREATION")
	private String poCreation;
	
	@DynamoDBAttribute(attributeName = "CREATION_DATE")
	private String creationDate;

	@DynamoDBAttribute(attributeName = "CREATION_TIME")
	private Long creationTime;

	@DynamoDBAttribute(attributeName = "Archive_doc_ID")
	private String archiveDocId;

	@DynamoDBAttribute(attributeName = "FNCA_DOC_TYPE")
	private String fncaDocType;

	@DynamoDBAttribute(attributeName = "COCD_DESCRIPTION")
	private String cocdDescription;

	@DynamoDBAttribute(attributeName = "VENDOR_ID")
	private String vendorId;

	@DynamoDBAttribute(attributeName = "VENDOR_NAME")
	private String vendorName;

	@DynamoDBAttribute(attributeName = "PURCHASING_ORG")
	private String purchasingOrg;

	@DynamoDBAttribute(attributeName = "PAYMENT_CE")
	private String paymentCe;

	@DynamoDBAttribute(attributeName = "PAYMENT_DOC#")
	private String paymentDocNum;

	@DynamoDBAttribute(attributeName = "PERIOD")
	private String period;

	@DynamoDBAttribute(attributeName = "REQ_TYPE")
	private String reqType;

	@DynamoDBAttribute(attributeName = "ENTERED_BY")
	private String enteredBY;

	@DynamoDBAttribute(attributeName = "ENTRY_DATE")
	private String entryDate;

	@DynamoDBAttribute(attributeName = "FILENAME")
	private String fileName;

	@DynamoDBAttribute(attributeName = "CONTENT_REP_TYP")
	private String CONTENT_REP_TYP;

	@DynamoDBAttribute(attributeName = "DOCUMENT_LINK")
	private String documentLink;

	@DynamoDBAttribute(attributeName = "Doc_Checksum")
	private String Doc_Checksum;

	@DynamoDBAttribute(attributeName = "Doc_AnnotContent")
	private String Doc_AnnotContent;

}