package com.smartKrow.model;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedTimestamp;

import lombok.Data;

@Data
@DynamoDBTable(tableName = "ZFADOCO")
public class ZFADOCO extends CommonFields{

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	@DynamoDBAttribute(attributeName = "document_id")
	private String documentId;

	@DynamoDBAttribute(attributeName = "application_type")
	private String applicationType;

	@DynamoDBAttribute(attributeName = "ASSET NUM")
	private String assetNum;

//	@DynamoDBAttribute(attributeName = "TRANSAC ID")
//	private String docNumber;

	//@DynamoDBTypeConvertedTimestamp
	@DynamoDBAttribute(attributeName = "CREATION_DATE")
	private String creationDate;

	@DynamoDBAttribute(attributeName = "CREATION_TIME")
	private Long creationTime;

	@DynamoDBAttribute(attributeName = "ARCHIVE_DOC_ID")
	private String archiveDocId;

	@DynamoDBAttribute(attributeName = "FNCA_DOC_TYPE")
	private String fncaDocType;

	@DynamoDBAttribute(attributeName = "COCD_DESCRIPTION")
	private String cocdDescription;

	@DynamoDBAttribute(attributeName = "ASSET DESCRIP2")
	private String assetDescrip2;

	@DynamoDBAttribute(attributeName = "ASSET DESCRIP1")
	private String assetDescrip1;

	@DynamoDBAttribute(attributeName = "ASSET CLASS")
	private String assetClass;

	@DynamoDBAttribute(attributeName = "ASSET MAIN NO.")
	private String assetMainNo;

	@DynamoDBAttribute(attributeName = "ACC DETERMINATI")
	private String accDeterminanti;

	@DynamoDBAttribute(attributeName = "ENTERED_BY")
	private String enteredBy;

	//@DynamoDBTypeConvertedTimestamp
	@DynamoDBAttribute(attributeName = "ENTRY_DATE")
	private String entryDate;

	@DynamoDBAttribute(attributeName = "DOCUMENT_LINK")
	private String documentLink;

}
