package com.archiveapi.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data
@NoArgsConstructor
@AllArgsConstructor
public class CommonFields {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	@DynamoDBAttribute(attributeName = "document_id")
	private String documentId;

	@DynamoDBAttribute(attributeName = "application_type")
	private String applicationType;
	

	@DynamoDBAttribute(attributeName = "Archive_doc_ID")
	private String Archive_doc_ID;

	@DynamoDBAttribute(attributeName = "FNCA_DOC_TYPE")
	private String FNCA_DOC_TYPE;

	@DynamoDBAttribute(attributeName = "COCD_DESCRIPTION")
	private String COCD_DESCRIPTION;

	@DynamoDBAttribute(attributeName = "VENDOR_ID")
	private String VENDOR_ID;

	@DynamoDBAttribute(attributeName = "VENDOR_NAME")
	private String VENDOR_NAME;

	@DynamoDBAttribute(attributeName = "PURCHASING_ORG")
	private String PURCHASING_ORG;

	@DynamoDBAttribute(attributeName = "PAYMENT_CE")
	private String PAYMENT_CE;

	@DynamoDBAttribute(attributeName = "PAYMENT_DOC#")
	private String PAYMENT_DOC_NUM;

	@DynamoDBAttribute(attributeName = "REQ_TYPE")
	private String REQ_TYPE;

	@DynamoDBAttribute(attributeName = "COCD")
	private String cocd;

	@DynamoDBAttribute(attributeName = "YEAR")
	private int YEAR;
	
	@DynamoDBAttribute(attributeName = "DOC_NUMBER")
	private String docNumber;
	
	@DynamoDBAttribute(attributeName = "PHC_NUMBER")
	private String PHC_NUMBER;
	
	@DynamoDBAttribute(attributeName = "NAME2")
	private String name2;
	
	@DynamoDBAttribute(attributeName = "TRANSAC ID")
	private String transacId;
	
	@DynamoDBAttribute(attributeName = "MAT_DOC")
	private String matDoc;
	
	@DynamoDBAttribute(attributeName = "START DATE")
	private String startDate;
	
	@DynamoDBAttribute(attributeName = "ASSET NUM ")
	private String assetNum;

	@DynamoDBAttribute(attributeName = "YEAR")
	private String year;
	
	//@DynamoDBTypeConvertedTimestamp
	@DynamoDBAttribute(attributeName = "CREATION_DATE")
	private String creationDate;

	@DynamoDBAttribute(attributeName = "CREATION_TIME")
	private Long creationTime;

	@DynamoDBAttribute(attributeName = "ARCHIVE_DOC_ID")
	private String archiveDocId;

	@DynamoDBAttribute(attributeName = "FNCA_DOC_TYPE")
	private String fncaDocType;

	@DynamoDBAttribute(attributeName = "FNCA_PO_TYPE")
	private String fncaPoType;
	
	@DynamoDBAttribute(attributeName = "COCD_DESCRIPTION")
	private String cocdDescription;
	
	@DynamoDBAttribute(attributeName = "END DATE")
	private String endDate;

	@DynamoDBAttribute(attributeName = "VENDOR_ID")
	private String vendorId;

	@DynamoDBAttribute(attributeName = "VENDOR_NAME")
	private String vendorName;

	@DynamoDBAttribute(attributeName = "DOC_TYPE_DESCRIPTION")
	private String docTypeDescription;

	//@DynamoDBTypeConvertedTimestamp
	@DynamoDBAttribute(attributeName = "POSTING_DATE")
	private String postingDate;

	@DynamoDBAttribute(attributeName = "DOCUMENT_DATE")
	private String documentDate;

	@DynamoDBAttribute(attributeName = "AMOUNT_LC")
	private String amountLc;

	@DynamoDBAttribute(attributeName = "AMT_GRP_CURRENC")
	private String amtGrpCurrenc;

	@DynamoDBAttribute(attributeName = "PAYMENT_REFEREN")
	private String paymentReferen;

	@DynamoDBAttribute(attributeName = "ASSIGNMENT")
	private String assignment;

	@DynamoDBAttribute(attributeName = "CLEARING_DOC")
	private String clearingDoc;

	//@DynamoDBTypeConvertedTimestamp
	@DynamoDBAttribute(attributeName = "CLEAR_DATE")
	private String clearDate;

	@DynamoDBAttribute(attributeName = "ENTERED_BY")
	private String enteredBy;

	//@DynamoDBTypeConvertedTimestamp
	@DynamoDBAttribute(attributeName = "ENTRY_DATE")
	private String entryDate;

	@DynamoDBAttribute(attributeName = "CURR")
	private String curr;

	@DynamoDBAttribute(attributeName = "DOC_HEADER_TEXT")
	private String docHeaderText;

	@DynamoDBAttribute(attributeName = "REFERENCE")
	private String reference;

	@DynamoDBAttribute(attributeName = "FILENAME")
	private String fileName;

	@DynamoDBAttribute(attributeName = "CONTENT_REP_TYP")
	private String contentRepTyp;

	@DynamoDBAttribute(attributeName = "GROUP_CURR")
	private String groupCurr;

	@DynamoDBAttribute(attributeName = "DOCUMENT_LINK")
	private String documentLink;

	@DynamoDBAttribute(attributeName = "Doc_Checksum")
	private String docChecksum;

	@DynamoDBAttribute(attributeName = "Doc_AnnotContent")
	private String docAnnotContent;

	@DynamoDBAttribute(attributeName = "APLL bL Number")
	private String apllBlnumber;

	@DynamoDBAttribute(attributeName = "Agent")
	private String agent;

	@DynamoDBAttribute(attributeName = "BL Number")
	private String blNumber;

	@DynamoDBAttribute(attributeName = "Cash Report Number")
	private String cashReportNumber;

	@DynamoDBAttribute(attributeName = "Document Processing Status")
	private String documnetProcessingStatus;

	@DynamoDBAttribute(attributeName = "Document type")
	private String documentType;

	@DynamoDBAttribute(attributeName = "f_entrydate")
	private String fEntryDate;

	@DynamoDBAttribute(attributeName = "Is Document Number")
	private String isDocumentNumber;

	@DynamoDBAttribute(attributeName = "No of Pages")
	private String noOfPages;

	@DynamoDBAttribute(attributeName = "Payment Amount")
	private String paymentAmount;

	@DynamoDBAttribute(attributeName = "Payment Date")
	private String paymentDate;

	@DynamoDBAttribute(attributeName = "Reference number")
	private String referenceNumber;

	@DynamoDBAttribute(attributeName = "Scan Batch ID")
	private String scanBatchId;

	@DynamoDBAttribute(attributeName = "PO_NUMBER")
	private String poNumber;

	@DynamoDBAttribute(attributeName = "PO_TYPE_DESCRIPTION")
	private String poTypeDescription;

	@DynamoDBAttribute(attributeName = "COMPANY_CODE")
	private String companyCode;

	@DynamoDBAttribute(attributeName = "NET_AMT")
	private String netAmt;

	@DynamoDBAttribute(attributeName = "CURRENCY")
	private String currency;

	@DynamoDBAttribute(attributeName = "PURCHASE_GRP")
	private String purchseGrp;

	@DynamoDBAttribute(attributeName = "PO_CREATOR")
	private String poCreator;

	@DynamoDBAttribute(attributeName = "PURCHASING_ORG")
	private String purchasingOrg;

	@DynamoDBAttribute(attributeName = "POCREATION")
	private String poCreation;

	@DynamoDBAttribute(attributeName = "Archive_doc_ID")
	private String archiveDocID;

	@DynamoDBAttribute(attributeName = "PAYMENT_CE")
	private String paymentCE;

	@DynamoDBAttribute(attributeName = "PAYMENT_DOC#")
	private String paymentDoc;

	@DynamoDBAttribute(attributeName = "PERIOD")
	private String period;

	@DynamoDBAttribute(attributeName = "REQ_TYPE")
	private String reqType;

	@DynamoDBAttribute(attributeName = "ENTERED_BY")
	private String ENTERED_BY;

	@DynamoDBAttribute(attributeName = "ENTRY_DATE")
	private String ENTRY_DATE;

	@DynamoDBAttribute(attributeName = "FILENAME")
	private String FILENAME;



	@DynamoDBAttribute(attributeName = "Doc_Checksum")
	private String Doc_Checksum;

	@DynamoDBAttribute(attributeName = "Doc_AnnotContent")
	private String Doc_AnnotContent;

	@DynamoDBAttribute(attributeName = "PHC_NUMBER")
	private String phcNumber;

	@DynamoDBAttribute(attributeName = "PAYMENT_CE")
	private String paymentCe;

	@DynamoDBAttribute(attributeName = "PAYMENT_DOC#")
	private String paymentDocNum;


	@DynamoDBAttribute(attributeName = "ENTERED_BY")
	private String enteredBY;
}
