package com.archiveapi.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@DynamoDBTable(tableName = "ZAPGFFUP")
@EqualsAndHashCode(callSuper = true)
public class ZAPGFFUP  extends CommonFields{
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	@DynamoDBAttribute(attributeName = "document_id")
	private String documentId;

	@DynamoDBAttribute(attributeName = "application_type")
	private String applicationType;

	@DynamoDBAttribute(attributeName = "DOC_NUMBER")
	private String docNumber;

	@DynamoDBAttribute(attributeName = "YEAR")
	private String year;
	
	@DynamoDBAttribute(attributeName = "COCD")
	private String cocd;

	//@DynamoDBTypeConvertedTimestamp
	@DynamoDBAttribute(attributeName = "CREATION_DATE")
	private String creationDate;

	@DynamoDBAttribute(attributeName = "CREATION_TIME")
	private Long creationTime;

	@DynamoDBAttribute(attributeName = "ARCHIVE_DOC_ID")
	private String archiveDocId;

	@DynamoDBAttribute(attributeName = "FNCA_DOC_TYPE")
	private String fncaDocType;

	@DynamoDBAttribute(attributeName = "COCD_DESCRIPTION")
	private String cocdDescription;

	@DynamoDBAttribute(attributeName = "VENDOR_ID")
	private String vendorId;

	@DynamoDBAttribute(attributeName = "VENDOR_NAME")
	private String vendorName;

	@DynamoDBAttribute(attributeName = "DOC_TYPE_DESCRIPTION")
	private String docTypeDescription;

	//@DynamoDBTypeConvertedTimestamp
	@DynamoDBAttribute(attributeName = "POSTING_DATE")
	private String postingDate;

	@DynamoDBAttribute(attributeName = "DOCUMENT_DATE")
	private String documentDate;

	@DynamoDBAttribute(attributeName = "AMOUNT_LC")
	private String amountLc;

	@DynamoDBAttribute(attributeName = "AMT_GRP_CURRENC")
	private String amtGrpCurrenc;

	@DynamoDBAttribute(attributeName = "PAYMENT_REFEREN")
	private String paymentReference;

	@DynamoDBAttribute(attributeName = "ASSIGNMENT")
	private String assignment;

	@DynamoDBAttribute(attributeName = "CLEARING_DOC")
	private String clearingDoc;

	//@DynamoDBTypeConvertedTimestamp
	@DynamoDBAttribute(attributeName = "CLEAR_DATE")
	private String clearDate;

	@DynamoDBAttribute(attributeName = "ENTERED_BY")
	private String enteredBy;

	//@DynamoDBTypeConvertedTimestamp
	@DynamoDBAttribute(attributeName = "ENTRY_DATE")
	private String entryDate;

	@DynamoDBAttribute(attributeName = "CURR")
	private String curr;

	@DynamoDBAttribute(attributeName = "DOC_HEADER_TEXT")
	private String docHeaderText;

	@DynamoDBAttribute(attributeName = "REFERENCE")
	private String reference;

	@DynamoDBAttribute(attributeName = "FILENAME")
	private String filename;

	@DynamoDBAttribute(attributeName = "CONTENT_REP_TYP")
	private String contentRepTyp;

	@DynamoDBAttribute(attributeName = "GROUP_CURR")
	private String groupCurr;

	@DynamoDBAttribute(attributeName = "DOCUMENT_LINK")
	private String documentLink;

	@DynamoDBAttribute(attributeName = "Doc_Checksum")
	private String docChecksum;

	@DynamoDBAttribute(attributeName = "Doc_AnnotContent")
	private String docAnnotContent;
}
