package com.archiveapi.model;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedTimestamp;

import lombok.Data;


@Data
@DynamoDBTable(tableName = "ZPCIMDOCT")
public class ZPCIMDOCT extends CommonFields{

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	@DynamoDBAttribute(attributeName = "document_id")
	private String documentId;

	@DynamoDBAttribute(attributeName = "application_type")
	private String applicationType;

	@DynamoDBAttribute(attributeName = "MAT_DOC")
	private String matDoc;

	@DynamoDBAttribute(attributeName = "YEAR")
	private String year;

	//@DynamoDBTypeConvertedTimestamp
	@DynamoDBAttribute(attributeName = "CREATION_DATE")
	private String creationDate;

	@DynamoDBAttribute(attributeName = "CREATION_TIME")
	private Long creationTime;

	@DynamoDBAttribute(attributeName = "ARCHIVE_DOC_ID")
	private String archiveDocId;

	@DynamoDBAttribute(attributeName = "FNCA_DOC_TYPE")
	private String fncaDocType;

	@DynamoDBAttribute(attributeName = "COCD_DESCRIPTION")
	private String cocdDescription;

	//@DynamoDBTypeConvertedTimestamp
	@DynamoDBAttribute(attributeName = "POSTING_DATE")
	private String postingDate;

	@DynamoDBAttribute(attributeName = "DOCUMENT_DATEX")
	private String documentDateX;

	@DynamoDBAttribute(attributeName = "ENTERED_BY")
	private String enteredBy;

	//@DynamoDBTypeConvertedTimestamp
	@DynamoDBAttribute(attributeName = "ENTRY_DATE")
	private String entryDate;

	@DynamoDBAttribute(attributeName = "DOCUMENT_LINK")
	private String documentLink;
}
